### ISSUE TITLE
Error uploading over 2mb - !Input::hasFile('file_data')

### ISSUE THREAD

**Issue by kdon80** [responsiv/uploader-plugin#14]
I noticed many of my pictures don't get loaded. It shows the upload is spinning and nothing happens. I tried many image sizes of the same image. Size 2.22 mb fails, while size 2.03 works.
As additional info, I set the maxSize to 10 in the plugin property.

I traced the javascript code and added console error message, then I saw there is an **error: 'File missing from request'**
I finally traced it to  ComponentUtils.checkUploadAction() and somehow **this is false:**

```
Input::hasFile('file_data')
```

**I added  console.log('error ' + error); in uploader.js:**

```
FileUpload.prototype.onUploadError = function(file, error) {
    console.log('error ' + error);
    var $preview = $(file.previewElement)
    $preview.addClass('is-error')
}
```

**ComponentUtils.php**

```
protected function checkUploadAction()
{
    if (!($uniqueId = Request::header('X-OCTOBER-FILEUPLOAD')) || $uniqueId != $this->alias) {
        return;
    }

    try {
        if (!Input::hasFile('file_data')) {
            throw new ApplicationException('File missing from request');
        }
```

**Comment by ametad** [comment]
Perhaps this is also useful: #16 ?

**Comment by kdoonboli** [comment]
@ametad Thanks, I tried your suggestion, but this seems to be another issue with file creation.

**Comment by kdon80** [comment]
I noticed my problem was with the php.ini on the server, by default it is set to 2mb.
