### ISSUE TITLE
Max size validation in component not used

### ISSUE THREAD

**Issue by ametad** [responsiv/uploader-plugin#16]
Hi there,

I noticed that when the 'maxSize' is set in the FileUploader component it does not do anything on validation. 

In the code you can see something else is used: https://github.com/responsiv/uploader-plugin/blob/master/traits/ComponentUtils.php#L114

```
            $validationRules = ['max:'.File::getMaxFilesize()];
            if ($fileTypes = $this->processFileTypes()) {
                $validationRules[] = 'extensions:'.$fileTypes;
            }
```

Could this be refactored to:

```
            $maxFilesize = $this->property('maxSize', File::getMaxFilesize());
            $validationRules = ['max:'.$maxFilesize];
            if ($fileTypes = $this->processFileTypes()) {
                $validationRules[] = 'extensions:'.$fileTypes;
            }
```

I think this is in line with the rest of the code.

**Comment by kdon80** [comment]
one thing to note, the property maxSize is supposed to be in MB, but getMaxFilesize() is in bytes. So either convert property's maxSize from MB to bytes here, or the plugin's front end option should say enter in bytes.
