### ISSUE TITLE
Moved to AWS, script type="text/template" not working

### ISSUE THREAD

**Issue by kdoonboli** [responsiv/uploader-plugin#17]
I just moved to AWS, and noticed script type="text/template" does not work properly in image-single.htm. Notice how the open DIVs don't close. I tried making it simple, and removed everything inside the script block but one single <div></div>, then the output is similar, as it doesn't display the closing </div>.

```
    <!-- Template for new file -->
    <script type="text/template" id="uploaderTemplateimageUploader">

            <div class="upload-object dz-preview dz-file-preview">
                  <a
              href="javascript:;"
              class="upload-remove-button"
              data-request="imageUploader::onRemoveAttachment"
              data-request-confirm="Replace picture?"                 >
                    <div class="icon-container image">
                        <img data-dz-thumbnail class="avatar img-circle" style="width: 160px;height: 160px;" />
    </script>
```

This is what happens when I have single DIV

```
<script type="text/template" id="uploaderTemplateimageUploader">

    <div>

</script>
```

**Comment by daftspunk** [comment]
I'm at a loss. How do I replicate this?

**Comment by kdoonboli** [comment]
Found the issue! It seems like that I happened to add 'one extra' plugin when I migrated to AWS - ResponsiveImages. And that broke the code! I removed ResponsiveImages by author 'OFFLINE' and now it works again. Thanks
