### ISSUE TITLE
Init Page Problem

### ISSUE THREAD

**Issue by zimbar** [responsiv/uploader-plugin#18]
Hello,

I have this error on page load:

Method name must be a string
/var/www/html/october/plugins/responsiv/uploader/traits/ComponentUtils.php line 81

this is my code
# [fileUploader]

<?php
    function onInit()
    {
        $this->fileUploader->bindModel('avatar', $this->user);
    }
# ?>

```
{{ form_ajax('onUpdate', { role: 'form', model: user, files: true }) }}
        {% component 'fileUploader' %}
```

   {{  form_close }}

Thanks.

**Comment by imkane** [comment]
I have the same error, unfortunately :(

**Comment by daftspunk** [comment]
This plugin is not released yet. Make sure you are using `edgeUpdates` with October, this plugin is only compatible with the very latest codebase.

**Comment by imkane** [comment]
Ahh darn, any ideas when we'll be able to use it?  It looks to be exactly what I need for my project :)

**Comment by imkane** [comment]
FYI got the very latest bleeding-edge updates, updated composer and october.  Still the same error :(

**Comment by daftspunk** [comment]
Can you give more detail any, error messages? The early bug report gives nothing.

**Comment by imkane** [comment]
Sure!  I'm attempting the "Attaching the uploader (from component)" from your instructions.

In my Component:

```
public function init()
    {
        $component = $this->addComponent(
            'Responsiv\Uploader\Components\FileUploader',
            'fileUploader',
            ['deferredBinding' => false]
        );

        $component->bindModel('photos', PhotosModel::find(1));
    }
```

In my Model:
`public $attachMany = ['photos' => 'System\Models\File'];`

Error details from loading a page (/owners/photos):

Method name must be a string
\plugins\responsiv\uploader\traits\ComponentUtils.php line 82

TYPE = PHP Content
EXCEPTION = Symfony\Component\Debug\Exception\FatalErrorException

else {
            $list = $this->model
                **->{$this->attribute}()**
                ->orderBy('id', 'desc')
                ->get();
        }

**Comment by daftspunk** [comment]
I am using this exact code without error. You will need to prepare a sample theme that demonstrates the issue.

**Comment by daftspunk** [comment]
Relation

```
    public $attachMany = [
        'files' => ['System\Models\File'],
    ];
```

PHP

```
        if (($project = $this->project()) && $project->isOwner()) {
            $component = $this->addComponent('fileUploader', 'editFileUploader', ['deferredBinding' => false]);
            $component->bindModel('files', $project);
        }
```

HTML

```
    {{ form_ajax('onEditFiles', {
        update: { 'project/files': '#partialProjectFiles' },
        class: 'ui small form'
    }) }}
        <div class="ui segment">
            {% component 'editFileUploader' %}
        </div>

        <button type="submit" class="ui positive tiny button">Finish editing</button>
    {{ form_close() }}
```

**Comment by imkane** [comment]
I'm not sure how to do that, as my customized theme uses a custom plugin that I created.  The theme by itself won't be useful for debugging this.

I hired a guy to help out so maybe he can figure it out.  I'll let you know.

**Comment by imkane** [comment]
Ok, so Anand was able to fix this, it just required:

```
<?php
function onInit()
{
    $this->fileUploader->bindModel('photos', new Kane\Listings\Models\Photos);
}
?>
```

Added to the Page :)
