### ISSUE TITLE
Class 'FileUploader' not found

### ISSUE THREAD

**Issue by nozreh** [responsiv/uploader-plugin#2]
I have tried using the plugin and added FileUploader model class, but still this is not working,
seems the binding is not working properly

**Comment by daftspunk** [comment]
This plugin is a work in progress.

**Comment by nozreh** [comment]
Hi George,

I know this is not yet a complete plugin, but I want to use it anyway can you help me point to right direction? I just want to create a plugin that will make frontend user upload a csv file and save the data in the database and then manage it from there

Thanks,
