### ISSUE TITLE
Form always renders showing records attached to model with id 0f 1

### ISSUE THREAD

**Issue by firemankurt** [responsiv/uploader-plugin#25]
Trying to use Responsiv\Uploader in a plugin but when the form renders on frontend page  it always shows the files attached to the model with id of 1.  Everything works in Backend.

Model:

```
public $attachMany = [
    'forms' => ['System\Models\File'],
];
```

Component:

```
public function init() {
    $this->doc = Doc::find(8);

    $component = $this->addComponent(
        'Responsiv\Uploader\Components\FileUploader',
        'fileUploader',
        [
            'placeholderText' => 'Do It',
            'deferredBinding' => false,
            'fileTypes' => 'pdf',
            'maxSize' => '3',
        ]
    );

    $component->bindModel('forms', $this->doc);
}
```

view:

<p>{{ __SELF__.doc.title }}</p>

{{ form_open() }}
   
   {% component 'fileUploader' %}
  {{ form_submit() }} 
{{ form_close() }}

**Comment by firemankurt** [comment]
Sent daftspunk an email with link to repo of plugin that I am working on where this issue occured in hopes to make it easier to reproduce.  
VendorUpload is the component name.

**Comment by firemankurt** [comment]
This line tries to load a property that does not exist:
https://github.com/responsiv/uploader-plugin/blob/2812f288b696d471cb228fed860624b464a75dd8/components/FileUploader.php#L106

**Comment by daftspunk** [comment]
It's for use like this

```
{% component 'fileUpload' populated=model.file %}
```

**Comment by firemankurt** [comment]
So I have boiled the issue down a bit but can not quite pin point the problem.  Using the following code I discovered that the model changes between the Init() and the onRun()

```
public function init() {

    $this->doc = Doc::find(10);

    $this->fuComponent = $this->addComponent(
        'Responsiv\Uploader\Components\FileUploader',
        'fileUploader',
        [
            'placeholderText' => 'Do It',
            //'modelKeyColumn' => 'id',
            'deferredBinding' => false,
            'fileTypes' => 'pdf',
            'maxSize' => '3',
        ]
    );

    $this->fuComponent->bindModel('forms', $this->doc);

            // Uncomment line below shows and ID of 10
    //var_dump($this->fuComponent->model->id);
}

public function onRun() {
            // Uncomment line below shows and ID of 1
    //var_dump($this->fuComponent->model->id);die(); 
}
```

**Comment by daftspunk** [comment]
`onRun` is called when the component renders so it is quite possible that the model will be changed. Take a look at the plugin documentation/readme for working examples. You can also find an example of this plugin in action [here](http://lancezero.com/project-submit) (second step).

**Comment by firemankurt** [comment]
Changing the relationship from "forms" to "files" seems to have fixed my issue.

So instead of:
    $this->fuComponent->bindModel('forms', $this->doc);
Do:
    $this->fuComponent->bindModel('files', $this->doc);

and use that in model when defining the relationship.
