### ISSUE TITLE
Attribute name must be a string, NULL was passed.

### ISSUE THREAD

**Issue by hambern** [responsiv/uploader-plugin#29]
I constantly get the error message:

> Attribute name must be a string, NULL was passed. plugins/responsiv/uploader/traits/ComponentUtils.php line 79

In component

``` php
use Hambern\Request\Models\Request;

class Form extends ComponentBase
{
    public function init()
    {
        $component = $this->addComponent(
            'Responsiv\Uploader\Components\ImageUploader',
            'imageUploader',
            ['deferredBinding' => true]
        );
        $component->bindModel('pictures', new Request);
    }
...
}
```

In model

``` php
use Model;

class Request extends Model
{
    ...
    public $attachMany = [
        'pictures' => ['System\Models\File'],
        'files'    => ['System\Models\File'],
    ];
}
```

In partial

``` html
{{ form_ajax('Form::onRequest', {
  update: { 'message': '#form_answer' }
}) }}
  <div class="row">
    <div class="twelve columns">
      {% component 'imageUploader' %}
      <button type"submit" class="button">Send »</button>
    </div>
  </div>
{{ form_close() }}
```

And the imageUploader and the Form component is added to the Layout.

``` html
[Form]

[imageUploader]
placeholderText = "Click or drag images to upload"
maxSize = 5
fileTypes = ".gif,.jpg,.jpeg,.png"
imageWidth = 100
imageHeight = 100
imageMode = "crop"
```

Please help me. If i dump the class `ComponentUtils` it seems like the bindModel-function is called twice. The first time everything looks correct, but the second time (??) the `$attribute` is NULL. Why?

**Comment by hambern** [comment]
Solved it! When you do the component-approach. You do not need to attach the imageUploader-component to the page or layout :)

But now I get this when trying to delete an uploaded file:

> AJAX handler 'imageUploader::onRemoveAttachment' could not be found

I guess the addComponent('Responsiv\Uploader\Components\ImageUploader') does not add the ajax handlers. What's the best way around this, if I add the component I get the error above.

**Comment by daftspunk** [comment]
If you use `$this->addComponent` then you don't need to include `[imageUploader]` on the page. Just add `[Form]`. It would appear you are adding the component twice, the second time is clearing the initialization.
