### ISSUE TITLE
[Question] Prevent form submission while uploading the file.

### ISSUE THREAD

**Issue by alvaro-canepa** [responsiv/uploader-plugin#30]
Is possible to know when the file is uploading to disable send buttons, and enable when file was uploaded?

**Comment by rajakhoury** [comment]
I added custom events in the plugin's JS inside ` FileUpload.prototype.bindUploader`

        // custom jquery events
        this.dropzone.on("queuecomplete", function (file) {
            if (this.getUploadingFiles().length === 0 && this.getQueuedFiles().length === 0) {
                $.event.trigger({
                    type: "uploadfinished",
                    message: "Dropzone Files upload finished",
                });
            }
        });
        this.dropzone.on("sending", function (file) {
            $.event.trigger({
                type: "uploadstarted",
                message: "Dropzone File upload started",
            });
        });

then you can in your form listent for these events to enable/disable the form button

        $(document).on("uploadfinished", function(event){
            submitBtn.prop('disabled', false)
        });
        $(document).on("uploadstarted", function(event){
            submitBtn.prop('disabled', true)
        });

Not sure this is the best way, i'm open to better implementation.

**Comment by alvaro-canepa** [comment]
Thanks @rajakhoury , this is exactly what i need. Maybe you can add a Pull Request with that!

Thanks allot..
