### ISSUE TITLE
after installing unable to parse error

### ISSUE THREAD

**Issue by yeomann** [responsiv/uploader-plugin#36]
Hi, thanks for great plugin, unfortunately, it broke my october im receving errors everywhere try to open builder from backend error try to open anything else from menu, you bet, Error! I tried using plugin refresh command, same thing error.

```
vagrant@scotchbox:/var/www/public$ php artisan plugin:refresh Responsiv.Uploader
Rolled back: Responsiv.Uploader
Reinstalling plugin...


  [Symfony\Component\Yaml\Exception\ParseException]
  Unable to parse at line 1 (near "
                              ").

```

try to force upload from plugin backend, same error again. I tried deleting using plugin:remove and same thing again.

UPDATE: my october is completely broke broke now. i recieve this error on every click almost. i clear the cache etc using artisan and logout for hard refresh but now i can not login it says `Unable to parse at line 1 (near "").` GOD 😢 

UPDATE: me again so sorry but i just wanted to let you know that i did `php artisan october:down` successfully while it failed on bring up 😯 

```
 php artisan october:up


  [Symfony\Component\Yaml\Exception\ParseException]
  Unable to parse at line 1 (near "















                         ").
```

**Comment by daftspunk** [comment]
The issue might be unrelated to this plugin. These errors are symptoms of a corrupt/incomplete filesystem.

**Comment by yeomann** [comment]
yes i know you are right! no doubt. but it really happened suddenly, i dig hard to find out that my version.yaml in updates folder was corrupted with wrong encoding. i had to recreate all DB. i guess we can close the issue.
