### ISSUE TITLE
How to get uploaded file

### ISSUE THREAD

**Issue by frankwhitejr** [responsiv/uploader-plugin#49]
Hi,

I have extended the user plugin and added the file uploader to the user account form which all works fine but i can't figure out how to get the uploaded file and use it on other pages?

Thanks,

**Comment by oscarnevarezleal** [comment]
Hi @frankwhitejr , do you have a running example so I can see how far had you go?

**Comment by zukkofirelord** [comment]
I still wait for the answer

**Comment by LukeTowers** [comment]
If you've followed the instructions in https://github.com/responsiv/uploader-plugin#attaching-the-uploader-from-page, you simply have to call the relationship that you defined for the file model.

```php
$files = $user->files;
```

**Comment by zukkofirelord** [comment]
but when I access files and check files path. it return   
```
_uploader" => array:1 [▼
    "files" => ""
  ]
```

so I can't access `$files = $user->files;`

**Comment by LukeTowers** [comment]
What's the code you're using? Does the parent model exist when you attach files to it?

**Comment by zukkofirelord** [comment]
yes, I already follow documentation with defferedBinding, and my parent model have attached files with attachMany. it still has null values from files.
```

function onInit()
{
    $this->fileUploader->bindModel('files', new Model);
} 
```

**Comment by LukeTowers** [comment]
Need to see all of the code. Model, page, component usage, where you're trying to access the files, everything.

**Comment by zukkofirelord** [comment]
well thank you

my components

```

public function defineProperties()
    {
        return [
            'vacationId' => [
                'title'             => 'Trip ID',
                'type'              => 'integer',
                'validationPattern' => '^[0-9]+$',
                'validationMessage' => 'The Trip ID property can contain only numeric symbols'
            ]
}
public function init()
    {
        $component   = $this->addComponent(
            'Responsiv\Uploader\Components\FileUploader',
            'FileUploader',
            [
                'fileTypes'             => ' .pdf, .doc, .docx, .xls',
                'placeholderText'       => "Drag and drop file here or Browse File",
            ],
            ['deferredBinding' => false]
        );
        $component->bindModel('files', ($this->property('vacationId') ? Trip::find((int)$this->property('vacationId')) : new Vacation));
}

public function onSave(){
   $data = post();
    $vacation = new Vacation;
    $vacation->fill($data);
    $vacation->save(null, post('_session_key'));
}
```

My Model

   ```
 public $attachMany = [
        'files' => 'System\Models\File',
    ]
    protected $fillable = [
        'files'
    ];
```

view

```
{{ form_open({request: 'onSave', files : true}) }}
    {% component 'fileUploader' %}
       <button type="submit" class="btn btn-primary">
                        Create 
                    </button>
 {{ form_close() }}
```

**Comment by LukeTowers** [comment]
@zukkofirelord couple things:

1. You need to have deferredBinding enabled if you are going to try to attach files to models that don't exist yet
2. The fillable entry for files is not required, and may cause problems
3. If you're using AJAX requests you should be using form_ajax() not form_open()

Fix those and it should start working for you.
