### ISSUE TITLE
Does this plugin works for OctoberCms frontend?

### ISSUE THREAD

**Issue by joejoezidane** [responsiv/uploader-plugin#5]
Responsiv Team:

I'm trying to use your uploader plugin, but i'm unable to bind it with a model. 
Does this works for frontend? If so, how can I bind it to a model using a simple page?

I would really appreciate your help...

**Comment by romaldyminaya** [comment]
Hi @joejoezidane 

Try this: 

```
function onStart()
{
    $this->imageUploader->bindModel('avatar', $this->user);
}
```

> Note that I'm using this in a page that has the account component dropped inside so I  can use $this->user to refference the current user.

**Comment by romaldyminaya** [comment]
Solved!!!

@joejoezidane trye This :)

```
function onInit()
{
    $this->imageUploader->bindModel('avatar', $this->account->user());
}
```

In which account is the account component that I dragged into the page :)

> Hope it helps

**Comment by joejoezidane** [comment]
Thank you very much @romaldyminaya, i found a solution using another plugin.

**Comment by bkrajendra** [comment]
Why I'm Getting this error..
![errrr](https://cloud.githubusercontent.com/assets/994083/11018548/86cdbd14-85f4-11e5-8f1a-083c2c512b58.PNG)

**Comment by selique** [comment]
i have too this bug ! plz help i need fix !
![](http://image.prntscr.com/image/e2c8472f4b544daea0a2c5807186109c.png)

**Comment by leogiovanni** [comment]
Probably you have to define your model.

Something like this:

![image](https://user-images.githubusercontent.com/1030471/34108157-24803a7c-e3e6-11e7-9a11-1e44053fd718.png)
