### ISSUE TITLE
Model created several times

### ISSUE THREAD

**Issue by ghost** [responsiv/uploader-plugin#50]
Hi, I have a strange bug with the uploader plugin.

I have a model : Post with the following file attachment : 

    public $attachMany = [
        'files' => 'System\Models\File',
    ];

I have the following code in my html : 

    {{ form_open({ request: 'onSave' }) }}
      <input type="text" name="title" />
      {% component 'fileUploader' %}
      <button type="submit">Submit</button>
    {{ form_close() }}

And here is my onSave function : 

    function onSave() {
        $post = new Post;
        $post->name = post('title');
        $post->save(null, post('_session_key'));
    }

My problem is that, each time I upload a file, a new model is created. Don't know what to do to prevent that and attach all my files to only one model.

Any help would be greatly appreciated, thanks !

**Comment by ghost** [comment]
After looking at different issue queues, maybe it's related to an [octobercms bug](https://github.com/octobercms/october/issues/3501)

**Comment by LukeTowers** [comment]
@PubliAlex this plugin isn't actually supported, it's more of a reference for how you could implement things. If you find the solution feel free to make a PR and I'll review that but I don't have time to look into it myself for free.

**Comment by Denoder** [comment]
@LukeTowers see https://github.com/responsiv/uploader-plugin/pull/54

**Comment by daftspunk** [comment]
Thanks @Teranode! This should be fixed by #54
