### ISSUE TITLE
Uploader button not working

### ISSUE THREAD

**Issue by os-kingsley** [responsiv/uploader-plugin#51]
I downloaded and set up the uploader plugin but for some reason the button is not working. When i click on it nothing happens. This is my set up.
On the page
````
[imageUploader]
maxSize = "2"
fileTypes = "*"
deferredBinding = "1"
````
==
````
<?php
function onInit()
{
    $this->imageUploader->bindModel('allimage', new Advert);
}
?>`
````
==
````
{{ form_open() }}
    <!-- File uploader -->
    {% component 'imageUploader' %}
{{ form_close() }}
````
Then in my component file
````
public function onSubmit(){
 $advert = new Advert();
       $advert->title = Input::get('title');
       $advert->user_id = Auth::getUser()->id;
       $advert->save(null, post('_session_key'));
}
````
In my model i have 
````
  public $attachMany = [
        "allimage" => "System\Models\File"

         ];
````
The upload button just doesn't respond. What am i missing here?

**Comment by andrepo** [comment]
Hi Corymillz,

Looks like a JS error, do you mind checking your browser's JS console and
sharing the error message?

**Comment by os-kingsley** [comment]
The only thing in console about uploader.js is
>Uncaught TypeError: $(...).render is not a function
    at uploader.js:319
    at uploader.js:323

**Comment by LukeTowers** [comment]
@Corymillz it looks like you're not loading jQuery properly.

**Comment by os-kingsley** [comment]
@LukeTowers ... Yeah, That's it.  Thanks
