### ISSUE TITLE
Multiple instances of Plugin not working.

### ISSUE THREAD

**Issue by bkrajendra** [responsiv/uploader-plugin#59]
Plugin not working with two/multiple instances of component.

I tried following code
```
function onInit()
{
    $user = Auth::getUser();
    if($user){
        $this->imageUploader1->bindModel('avatar', $user);
        
        $profile = $user->profile;
        $this->imageUploader2->bindModel('familypic', $profile);
    }
}
```
with

```
{{ form_open() }}
            {% component 'imageUploader1' %}
{{ form_close() }}

{{ form_open() }}
            {% component 'imageUploader2' %}
{{ form_close() }}
```
Im trying this from page.
My problem is both my images get uploaded to avatar (imageUploader1)
even if I upload it though imageuploader2 it gets saved in avatar.

my model code is:

```
user model already has avatar
and 
Profile Model:
    public $attachOne = [
		'familypic' => ['System\Models\File']
    ];
```

I even tried following way in page itself.

```
function onInit()
{
    $user = Auth::getUser();
    if($user){
        $component1 = $this->addComponent(
            'Responsiv\Uploader\Components\ImageUploader',
            'imageUploader1',
            ['deferredBinding' => false]
        );

        $component1->bindModel('avatar', $user);
        
    }

    if($user){
 
        $component2 = $this->addComponent(
            'Responsiv\Uploader\Components\ImageUploader',
            'imageUploader2',
            ['deferredBinding' => false]
        );
        
        $profile = $user->profile;
        $component2->bindModel('familypic', $profile);        
        
    }
}
```

Please help.

**Comment by LukeTowers** [comment]
Why on earth would `onInit2()` work??? What exactly do you mean by multiple instances? What is the end result you're trying to achieve?

**Comment by bkrajendra** [comment]
Hey @LukeTowers , that onInit2() came from my code page,
As im testing things I changed it to onInit2() to test another block of onInit.
You should ignore that.
Question is pretty straight. I want to have two image uploads on same page. One for user avatar pic another for my profile model familypic.
hence you can see imageUploader1 and imageUploader2 two instances i have created.

**Comment by daftspunk** [comment]
@bkrajendra refer to the following document: https://octobercms.com/docs/cms/components#aliases

> The aliases also allow you to define multiple components of the same class on a same page by using the short name first and an alias second. This lets you to use multiple instances of a same component on a page.

```
[demoTodo todoA]
maxItems = 10
[demoTodo todoB]
maxItems = 20
```

Hope this helps

**Comment by bkrajendra** [comment]
Hi @daftspunk 
Im trying to do exactly same thing as in this post https://github.com/responsiv/uploader-plugin/issues/4#issuecomment-196147712


but for me even if I upload second image it gets uploaded to avatar (First imageuploader)

I have added two imageuploader instances by dragging from components panel as you said.
I guess it should work without dragging/placing component on page if I use addComponent.?

**Comment by daftspunk** [comment]
@bkrajendra I have taken the time to test this for you

For next time, the theme template is what we need to properly understand your situation (you were close):

```
title = "Test"
url = "/test"
layout = "default"

[imageUploader imageUploader1]
[imageUploader imageUploader2]
==

function onInit() {
    $this->imageUploader1->bindModel('avatar', RainLab\User\Models\User::find(2));
    $this->imageUploader2->bindModel('avatar', RainLab\User\Models\User::find(3));
}
==

{% component 'imageUploader1' %}
{% component 'imageUploader2' %}
```

The following commit should resolve your issue 3a0df39c24c3d622c9f19024154d0fd524951940 and feel free to update your files accordingly

**Comment by bkrajendra** [comment]
Thanks a lot @daftspunk .
Its working now after making changes in 
components/imageuploader/image-multi.htm
```
data-upload-handler="{{ __SELF__ }}::onUpload"
```

I understand I should have given template code, but as i have mentioned about dragging components on page, I thought is enough to understand. 

But anyways thanks a lot for help.
I should have looked into plugin code, as I had this doubt about it as earlier same code worked for NETSI.uploader (which is removed now from plugin store)

**Comment by bkrajendra** [comment]
and most important!
My original code works great now.
It dont even need to add 
```
[imageUploader imageUploader1]
[imageUploader imageUploader2]

```
 in template code.

just use this in code section:

```
function onInit()
{

    
    $imageUploader1 = $this->addComponent(
            'Responsiv\Uploader\Components\ImageUploader',
            'imageUploader1',
            ['deferredBinding' => false]
        );
    $imageUploader2 = $this->addComponent(
            'Responsiv\Uploader\Components\ImageUploader',
            'imageUploader2',
            ['deferredBinding' => false]
        );
        
    $user = Auth::getUser();
    $profile = $user->profile;
    
    $imageUploader1->bindModel('avatar', $user);
    $imageUploader2->bindModel('familypic', $profile);
    
}
```
