### ISSUE TITLE
Asset combining not working for addCss and addJs using arrays

### ISSUE THREAD

**Issue by Tony-S** [responsiv/uploader-plugin#61]
Version 1.0.5 uses the following in the file uploader component fileUploader.php:
```
public function onRun()
    {
        $this->addCss(['assets/css/uploader.css']);
        $this->addJs([
            'assets/vendor/dropzone/dropzone.js',
            'assets/js/uploader.js',
        ]);

        $this->autoPopulate();
    }
```
This uses arrays to pass the asset paths. On my installation , this results in an error:
The source "/plugins/responsiv/uploader/assets/css/uploader.css" is not in the root directory "/home/xxx/public_html/oct".
This is with latest October (465) and version 1.0.5 of file uploader.
Changing just this function back to the 1.0.4 version gets everything working:
```
    public function onRun()
    {
        $this->addCss('assets/css/uploader.css');
        $this->addJs('assets/vendor/dropzone/dropzone.js');
        $this->addJs('assets/js/uploader.js');

        $this->autoPopulate();
    }
```
This seems to relate to issue https://github.com/octobercms/october/issues/3264 and following it through in the debugger it seems to be presenting relative paths to the asset combiner not absolute ones, and that breaks it. I guess it's working ok for other people and the docs say using arrays for the assets is fine, but it doesn't work for me. October is installed in the oct folder of the web root. I'm guessing that this might be an October or installation issue rather than a file uploader issue but I haven't been able to find anything that gives me a solution other than changing the code in the onRun function. I have many other downloaded and created plugins that all work fine and it was only when I upgraded the file uploader that it broke.

**Comment by LukeTowers** [comment]
@Tony-S can you verify that the changes made in https://github.com/octobercms/october/commit/aeb7616d063121d47cfb5aefe07fa9524e4a522b are actually present in your local files?

**Comment by Tony-S** [comment]
Hi - No, those changes aren't in my files so that would explain it! I've just updated OC using composer and it says build 465 in the backend but it looks like something hasn't worked. I shall have to look into that - thanks for your question as it's pointed out the issue.

**Comment by LukeTowers** [comment]
@Tony-S  See https://github.com/octobercms/october/pull/4615 for a bit more explanation on why that would be the case. Make sure that you're using PHP > 7.2 (or at the very least > 7.0, but I highly recommend > 7.2) and try running composer update again.

**Comment by Tony-S** [comment]
@LukeTowers Yes, using 7.2. I'd disabled core updates in config which might relate but the real issue was that I was using  cyd293 backendskin plugin which overwrites AssetMaker.php with its own copy and is out of date for the changes (and not a maintainable way to do things). Once I realised that the copy of AssetMaker open in my IDE was from this plugin, not from core, the confusion lifted! All sorted now. Thanks again for your great and fast help.

**Comment by LukeTowers** [comment]
No problem @Tony-S! If you rely on October for your business I'd highly recommend looking into getting a premium support plan: https://octobercms.com/premium-support
