### ISSUE TITLE
files not found 

### ISSUE THREAD

**Issue by zukkofirelord** [responsiv/uploader-plugin#63]
I want to upload files in pdf, jpg, ppt, etc. I have written the init function in the component as follows. 

`$component   = $this->addComponent(
            'Responsiv\Uploader\Components\FileUploader',
            'fileUploader',
            [
                'fileTypes'             => '.jpeg, .pdf, .doc, .docx,  .ppt, .pptx',
                'placeholderText'       => "Browse File",
            ],
            ['deferredBinding' => false]
        );
        $component->bindModel('files',  new Model));`

after uploading the output files return null values `"_uploader" => array:1 [▼
    "files" => ""
  ]` but it saved in storage. so how I can get files that I uploaded in storage ?

**Comment by LukeTowers** [comment]
@zukkofirelord see https://github.com/responsiv/uploader-plugin/issues/49#issuecomment-634184085
