### ISSUE TITLE
Codeception confused trying to submit the form with uploader

### ISSUE THREAD

**Issue by vdomah** [responsiv/uploader-plugin#64]
After inserting uploader component into my form Codeception stopped to understand where the submit button is. It says:
> [TestRuntimeException] Button is not inside a link or a form 

If I remove {% component 'fileUploader' %} from my form Codeception finds submit button inside the form easily. 

No html structure braking found. form tags are surrounding submit button properly

**Comment by LukeTowers** [comment]
Did you wrap your `{% component 'fileUploader' %}` inside of your form element?

**Comment by vdomah** [comment]
yes, exactly. The component is inside form

**Comment by LukeTowers** [comment]
Sounds like a problem to report to CodeCeption then
