### ISSUE TITLE
Files not sorting

### ISSUE THREAD

**Issue by evwerkz** [responsiv/uploader-plugin#72]
https://github.com/responsiv/uploader-plugin/blob/f99eb6b74417d5779f5c7707a8ffd231ea440e70/traits/ComponentUtils.php#L95

I noticed that the files are not sorted by 'DESC' at all.

![image](https://user-images.githubusercontent.com/49227960/158848907-dad5781c-af42-4bb7-8f16-5abbf76ae199.png)

**Comment by daftspunk** [comment]
This is likely being overruled by the sort order in the relation definition where `sort_order` column takes priority. So in effect, the sort order is `sort_order` then `id`.  We should probably remove this code to prevent confusion.
