### ISSUE TITLE
IOS "File Missing from request" Error

### ISSUE THREAD

**Issue by NielsvandenDries** [responsiv/uploader-plugin#74]
Good day all,
When I want to upload a photo with my phone (Iphone13) i got this error
`"File Missing from request"`
Some knows how to fix this?

Via PC it is working,

Niels

**Comment by NielsvandenDries** [comment]
I changed my php.ini
```
upload_max_filesize = 20M
post_max_size = 20M
```
Did not Fix the problem

**Comment by daftspunk** [comment]
This might be related to an outdated dropzone version

**Comment by NielsvandenDries** [comment]
> This might be related to an outdated dropzone version

Is there a solution for this issue, am i the only one having this problem?

**Comment by daftspunk** [comment]
Looks like it might be an issue with [dropzone and how iOS reports files](https://stackoverflow.com/questions/50698399/dropzone-js-not-working-using-ios). Some things to try first, though:

- Does it happen in the October CMS backend as well? It uses the latest dropzone
- Update dropzone to the latest in this plugin

**Comment by NielsvandenDries** [comment]
@daftspunk 

> Looks like it might be an issue with [dropzone and how iOS reports files](https://stackoverflow.com/questions/50698399/dropzone-js-not-working-using-ios). Some things to try first, though:
> 
> * Does it happen in the October CMS backend as well? It uses the latest dropzone
> * Update dropzone to the latest in this plugin

On the backend I can upload in media with iOS, but does it use the Responsiv Uploader plugin?

I'm going to see how to update dropzone, just got the plugin for the first time so I'll have to see how this works

**Comment by daftspunk** [comment]
October CMS has native support for file uploads via AJAX (and more recently downloads, too!). Since it is more modern, it should work with iOS.

Here is an example:

```html
<form data-request="onSubmit" data-request-files>
    <input type="file" name="photo" accept="image/*" />
    <button type="submit">Submit</button>
</form>
```
