### ISSUE TITLE
TypeError: undefined is not an object (evaluating '$.fn')

### ISSUE THREAD

**Issue by anik1ng** [responsiv/uploader-plugin#76]
Plugin doesn't work, I got error "TypeError: undefined is not an object (evaluating '$.fn')". How to solve this?

<img width="532" alt="Screenshot 2023-08-01 at 21 13 59" src="https://github.com/responsiv/uploader-plugin/assets/505388/91a00a6b-c0f9-48bb-a0b3-fc88d6a29f63">

October version 3.3.19

**Comment by daftspunk** [comment]
Hey @anik1ng 

This plugin depends on jQuery. Including it should fix this issue.
